### ISSUE TITLE
Linux x64 start failed

### ISSUE THREAD

**Issue by iamsimakov** [tversteeg/castle-game#19]
Hi, thank you for game. I downloaded last pre-release version, set executable flag and tried to run game:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:335:21
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
On this machine I have not rust compiler and maybe other build tools.
I would like to help you by giving feedback. 

md5sum 42b1dd4940e82d83af0102b09810b8e7  castle-linux-64bit
size 17791144

**Comment by tversteeg** [comment]
That's kind of odd, I have the same problem, no idea how I didn't notice that. This project is pretty dead but it seems 0.1.30 is still working on my machine.

**Comment by iamsimakov** [comment]
so, let me close this issue
