### ISSUE TITLE
cargo run --release

### ISSUE THREAD

**Issue by PierreTurnbull** [tversteeg/castle-game#2]
Hello, I am on Windows 10 and I followed your instructions to build and run the game. First, I installed CMake and made its path global. Then I cloned the repo and went in it. Then I typed `cargo run --release`, but my shell told me "command not found: cargo". I tried ./cargo, cargo.toml, ./Cargo.toml, etc... nothing worked. It seems that I can't use your sources.

**Comment by tversteeg** [comment]
Ah sorry, you need to install the Rust compiler and tools first: https://www.rustup.rs/

I'll add it to the readme, thanks for the heads up!
