### ISSUE TITLE
Bug: enemy melee pass through units

### ISSUE THREAD

**Issue by PierreTurnbull** [tversteeg/castle-game#5]
Enemy melee units pass through units, without stopping to attack mine, like if they didn't detect mine.
It happened also that my melee units pass through enemy units.

**Comment by tversteeg** [comment]
I made it like that on purpose so there wouldn't be a giant queue but the system is not perfect yet.

**Comment by tversteeg** [comment]
Do you have any suggestions on how I can make it so there won't be giant queues?

**Comment by PierreTurnbull** [comment]
With both constraints of 2D and high population army, I would suggest a functionality of "packing":
- when moving, units keep a normal distance between each other.
- when a soldier stops to perform an attack, soldiers behind would pass over that distance limit and pack themselves into a big melee, which could enable 4 or 5 soldiers at the same time to hit enemies. Archers would pack too in order to be more than just 1 guy to throw arrows.

Here is a [schema](https://zupimages.net/up/18/10/5iii.png) to illustrate my words.

Also, this functionality should be limited if armies are big. Maybe it would be interesting not making too many soldiers available at the same time.

**Comment by tversteeg** [comment]
That sounds like a really solid idea. I wanted to achieve something similar by making units move through other units which are fighting in close combat but I think this idea is a lot better. I'll add it to the TODO :)
