### ISSUE TITLE
Game is too big for the screen, and unresizable on top of that :(

### ISSUE THREAD

**Issue by AqilCont** [tversteeg/castle-game#53]
![image](https://user-images.githubusercontent.com/32044067/141215868-cb56900e-741c-41de-b07c-d87db1c1dd2e.png)

This is how the game is working on a windows laptop, there's no function for fullscreen, and the game spans two separate 1440p displays with no way to resize the window. Is it not possible to make it have smaller size or to make it resizable somehow?

**Comment by AqilCont** [comment]
This is a separate window that pops up, don't know if it's related or if I should create a separate issue for it.

![image](https://user-images.githubusercontent.com/32044067/141216143-d2ac2445-7a21-409c-a73e-3eae6d8d09d2.png)

**Comment by tversteeg** [comment]
I'm completely rewriting everything using the Bevy framework in the `bevy` branch. So this issue won't be relevant any longer.
